create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  pathname text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists app_events_created_at_idx
  on public.app_events (created_at desc);

create index if not exists app_events_event_type_idx
  on public.app_events (event_type);
