[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/fflogs-proxy"
  to = "/.netlify/functions/fflogs-proxy"
  status = 200

[[redirects]]
  from = "/api/log-event"
  to = "/.netlify/functions/log-event"
  status = 200

[[redirects]]
  from = "/api/build-info"
  to = "/.netlify/functions/build-info"
  status = 200

[[redirects]]
  from = "/api/analytics-summary"
  to = "/.netlify/functions/analytics-summary"
  status = 200
