// Core constants, state, DOM bindings, and debug helpers

const TUTORIAL_STATE_KEY = 'ffxiv_rotation_diff_tutorial';

const JOB_CODE_MAP = {
  PALADIN: 'PLD', WARRIOR: 'WAR', DARKKNIGHT: 'DRK', GUNBREAKER: 'GNB',
  WHITEMAGE: 'WHM', SCHOLAR: 'SCH', ASTROLOGIAN: 'AST', SAGE: 'SGE',
  MONK: 'MNK', DRAGOON: 'DRG', NINJA: 'NIN', SAMURAI: 'SAM', REAPER: 'RPR', VIPER: 'VPR',
  BARD: 'BRD', MACHINIST: 'MCH', DANCER: 'DNC',
  BLACKMAGE: 'BLM', SUMMONER: 'SMN', REDMAGE: 'RDM', PICTOMANCER: 'PCT',
  // already-abbreviated pass-through
  PLD: 'PLD', WAR: 'WAR', DRK: 'DRK', GNB: 'GNB',
  WHM: 'WHM', SCH: 'SCH', AST: 'AST', SGE: 'SGE',
  MNK: 'MNK', DRG: 'DRG', NIN: 'NIN', SAM: 'SAM', RPR: 'RPR', VPR: 'VPR',
  BRD: 'BRD', MCH: 'MCH', DNC: 'DNC',
  BLM: 'BLM', SMN: 'SMN', RDM: 'RDM', PCT: 'PCT',
};

const BURST_BUFFS = [
  { ids: [7398],  nameEn: 'Battle Litany',    nameJa: 'バトルリタニー',      duration: 20, color: '#60a5fa' },
  { ids: [7396],  nameEn: 'Brotherhood',       nameJa: '桃園結義',           duration: 20, color: '#f472b6' },
  { ids: [16552], nameEn: 'Divination',        nameJa: 'ディヴィネーション',   duration: 20, color: '#fbbf24' },
  { ids: [7436],  nameEn: 'Chain Stratagem',   nameJa: '連環計',             duration: 20, color: '#a78bfa' },
  { ids: [7520],  nameEn: 'Embolden',          nameJa: 'エンボルデン',        duration: 20, color: '#f87171' },
  { ids: [24405], nameEn: 'Arcane Circle',     nameJa: 'アルケインサークル',   duration: 20, color: '#c084fc' },
  { ids: [], nameEn: 'Quadruple Technical Finish', nameJa: 'クワッド・テクニカルフィニッシュ', duration: 20, color: '#34d399' },
  { ids: [25801], nameEn: 'Searing Light',     nameJa: 'シアリングライト',     duration: 20, color: '#fcd34d' },
  { ids: [25785], nameEn: 'Radiant Finale',    nameJa: '光神のフィナーレ',     duration: 20, color: '#fb923c' },
  { ids: [118, 25786], nameEn: 'Battle Voice',  nameJa: 'バトルボイス',         duration: 20, color: '#a3e635' },
  { ids: [], nameEn: 'Starry Muse',       nameJa: 'イマジンスカイ',       duration: 20, color: '#38bdf8' },
  { ids: [36871], nameEn: 'Dokumori',          nameJa: '毒盛り',             duration: 20, color: '#86efac' },
];

const SELF_BUFFS = [
  { nameEn: 'Fight or Flight',  nameJa: 'ファイト・オア・フライト', duration: 20, color: '#fbbf24' },
  { nameEn: 'Inner Release',    nameJa: '原初の解放',             duration: 15, color: '#ef4444' },
  { nameEn: 'Blood Weapon',     nameJa: 'ブラッドウェポン',       duration: 15, color: '#dc2626' },
  { nameEn: 'Delirium',         nameJa: 'ブラッドデリリアム',      duration: 15, color: '#b91c1c' },
  { nameEn: 'No Mercy',         nameJa: 'ノー・マーシー',         duration: 20, color: '#f59e0b' },
  { nameEn: 'Riddle of Fire',   nameJa: '紅蓮の極意',            duration: 20, color: '#ea580c' },
  { nameEn: 'Lance Charge',     nameJa: 'ランスチャージ',         duration: 20, color: '#3b82f6' },
  { nameEn: 'Raging Strikes',   nameJa: '猛者の撃',             duration: 20, color: '#f97316' },
  { nameEn: 'Wildfire',         nameJa: 'ワイルドファイア',       duration: 10, color: '#ef4444' },
  { nameEn: 'Devilment',        nameJa: '攻めのタンゴ',          duration: 20, color: '#ec4899' },
  { nameEn: 'Ley Lines',        nameJa: '黒魔紋',               duration: 30, color: '#8b5cf6' },
  { nameEn: 'Manafication',     nameJa: 'マナフィケーション',     duration: 15, color: '#6366f1' },
  { nameEn: 'Meikyo Shisui',    nameJa: '明鏡止水',             duration: 15, color: '#06b6d4' },
];

const JOB_NAME_JA = {
  PLD:'ナイト', WAR:'戦士', DRK:'暗黒騎士', GNB:'ガンブレイカー',
  WHM:'白魔道士', SCH:'学者', AST:'占星術師', SGE:'賢者',
  MNK:'モンク', DRG:'竜騎士', NIN:'忍者', SAM:'侍', RPR:'リーパー', VPR:'ヴァイパー',
  BRD:'吟遊詩人', MCH:'機工士', DNC:'踊り子',
  BLM:'黒魔道士', SMN:'召喚士', RDM:'赤魔道士', PCT:'ピクトマンサー',
};

const JOB_ROLE = {
  PLD:'T', WAR:'T', DRK:'T', GNB:'T',
  WHM:'H', SCH:'H', AST:'H', SGE:'H',
  MNK:'D', DRG:'D', NIN:'D', SAM:'D', RPR:'D', VPR:'D',
  BRD:'D', MCH:'D', DNC:'D',
  BLM:'D', SMN:'D', RDM:'D', PCT:'D',
};

const JOB_SHORT_JA = {
  PLD:'ナ', WAR:'戦', DRK:'暗', GNB:'ガ',
  WHM:'白', SCH:'学', AST:'占', SGE:'賢',
  MNK:'モ', DRG:'竜', NIN:'忍', SAM:'侍', RPR:'リ', VPR:'ヴ',
  BRD:'詩', MCH:'機', DNC:'踊',
  BLM:'黒', SMN:'召', RDM:'赤', PCT:'ピ',
};

const ROLE_ORDER = ['T','H','D'];

const I18N = {
  en: {
    siteTitle: 'FFXIV Skill Rotation Diff',
    siteDesc: 'Compare skill rotations from 2 public FFLogs URLs',
    step1Title: '1. Load Public FFLogs Logs',
    publicOnlyNote: 'Public FFLogs logs only. No FFLogs sign-in is required.',
    logUrlA: 'Log URL A',
    logUrlB: 'Log URL B',
    loadBtn: 'Load Reports',
    step2Title: '2. Select Fight Data (Kill only)',
    logAFight: 'Log A Fight',
    logBFight: 'Log B Fight',
    loadPlayersBtn: 'Get Players for This Fight',
    step3Title: '3. Select Players to Compare',
    logAPlayer: 'Log A Player',
    logBPlayer: 'Log B Player',
    compareBtn: 'Start Comparison',
    step4Title: '4. Comparison Results',
    tabAll: 'Full TL',
    tabOdd: 'Odd Min TL',
    tabEven: 'Even Min TL',
    laneAbility: 'Ability',
    laneGcd: 'WS / Spell',
    laneSynergy: 'Synergy',
    debugNormalTitle: 'Log',
    debugErrorTitle: 'Error Log',
    tutorialBtn: 'First time here?',
    contactBtn: 'Feedback / Request',
    authLoginSignup: 'Log in / Sign up',
    logoutBtn: 'Log out',
    usageRemaining: (remaining) => `Remaining today: ${remaining >= 9999 ? 'Unlimited' : remaining}`,
    statusLabel: 'Status:',
    statusFree: 'Free',
    statusSupporter: 'Supporter',
    bookmarkSave: 'Save bookmark',
    bookmarkList: 'Bookmarks',
    bookmarkModalTitle: 'Bookmarks',
    bookmarkSaved: 'Bookmark saved.',
    bookmarkDeleted: 'Bookmark deleted.',
    bookmarkPremiumOnly: 'Bookmarks are a Supporter-only feature.',
    bookmarkSavedAt: 'Saved:',
    bookmarkSaveFirst: 'Show comparison results before saving.',
    bookmarkLimitReached: 'You can save up to 100 bookmarks. Delete an old one first.',
    bookmarkSaveFailed: 'Failed to save bookmark.',
    bookmarkLoading: 'Loading...',
    bookmarkEmpty: 'No bookmarks saved.',
    bookmarkOpen: 'Open',
    bookmarkDelete: 'Delete',
    bookmarkDeleting: 'Deleting...',
    bookmarkDeleteFailed: 'Failed to delete bookmark.',
    bookmarkListFailed: 'Failed to load bookmarks.',
    tutorialPrev: 'Back',
    tutorialNext: 'Next',
    tutorialFinish: 'Done',
    tutorialClose: 'Close',
    tutorialWaiting: 'Waiting for this step to be completed.',
    tutorialReady: 'Completed. Move to the next step.',
    tutorialIntroTitle: 'Quick Start Guide',
    tutorialIntroBody: 'This guide walks you through the minimum steps needed to load two public logs and reach the comparison timeline.',
    tutorialLoadReportsTitle: '1. Enter two public log URLs',
    tutorialLoadReportsBody: 'Paste one FFLogs report URL into A and one into B, then load the reports. When the fight selectors appear, this step is complete.',
    tutorialLoadPlayersTitle: '2. Choose fights and load players',
    tutorialLoadPlayersBody: 'Pick the fight you want to compare from each log, then load the player list for both sides.',
    tutorialCompareTitle: '3. Choose players and start comparison',
    tutorialCompareBody: 'Select one player from each log and run the comparison. When the timeline panel opens, the main setup is complete.',
    tutorialDoneTitle: 'Guide Complete',
    tutorialDoneBody: 'The comparison view is now ready. You can switch tabs, change phase filters, zoom, and inspect the timeline freely.',
    tutorialStep: (current, total) => `Step ${current} / ${total}`,
    badUrl: 'Please check FFLogs URL format.',
    loading: 'Loading reports...',
    killFightsLoaded: (a,b) => `Kill fights loaded: A=${a} / B=${b}`,
    playersLoaded: (a,b) => `Players loaded: A=${a} / B=${b}`,
    tlLoading: 'Loading player timeline...',
    tlLoaded: (a,b) => `TL loaded: A=${a} / B=${b}`,
    compareFailed: (message) => `Comparison failed: ${message}`,
    timelineRenderFailed: (message) => `Timeline render failed: ${message}`,
    kill: 'Kill',
    wipe: 'Wipe',
    encounterMismatch: 'Cannot compare different bosses. Please select the same encounter.',
    phaseAll: 'All Phases',
    usageLimitReached: 'Daily limit of 30 reached. Supporters have unlimited comparisons.',
    usageCheckFailed: 'Failed to check usage. Please try again later.',
  },
  ja: {
    siteTitle: 'FFXIV Skill Codex',
    siteDesc: 'FFLogs の公開ログ URL 2 件からスキル回しを比較します',
    step1Title: '1. 公開 FFLogs ログを読み込む',
    logUrlA: 'ログURL A',
    logUrlB: 'ログURL B',
    loadBtn: '読み込み開始',
    step2Title: '2. 戦闘データ選択（Kill のみ）',
    logAFight: 'ログA 戦闘',
    logBFight: 'ログB 戦闘',
    loadPlayersBtn: 'この戦闘でプレイヤー一覧を取得',
    step3Title: '3. 比較するプレイヤー選択',
    logAPlayer: 'ログAプレイヤー',
    logBPlayer: 'ログBプレイヤー',
    compareBtn: '比較を開始',
    step4Title: '4. 比較結果',
    tabAll: '全体TL',
    tabOdd: '奇数分TL',
    tabEven: '偶数分TL',
    laneAbility: 'アビリティ',
    laneGcd: 'WS・魔法',
    laneSynergy: 'シナジー',
    debugNormalTitle: 'ログ',
    debugErrorTitle: 'エラーログ',
    publicOnlyNote: '公開ログのみ対応です。',
    badUrl: 'FFLogs URL形式を確認してください。',
    loading: 'レポートを読み込み中...',
    killFightsLoaded: (a,b) => `Kill戦闘一覧取得成功: A=${a}件 / B=${b}件`,
    playersLoaded: (a,b) => `プレイヤー取得成功: A=${a}人 / B=${b}人`,
    tlLoading: '選択プレイヤーのTLを取得中...',
    tlLoaded: (a,b) => `TL取得成功: A=${a}件 / B=${b}件`,
    compareFailed: (message) => `比較に失敗しました: ${message}`,
    timelineRenderFailed: (message) => `タイムライン描画に失敗しました: ${message}`,
    kill: 'Kill',
    wipe: 'Wipe',
    encounterMismatch: '異なるボスの戦闘は比較できません。同じ敵を選択してください。',
    phaseAll: '全フェーズ',
    tutorialBtn: '初めての方はこちら',
    contactBtn: 'ご要望フォーム',
    authLoginSignup: 'ログイン / 会員登録',
    logoutBtn: 'ログアウト',
    usageRemaining: (remaining) => `本日残り回数：${remaining >= 9999 ? '無制限' : remaining}`,
    statusLabel: 'ステータス：',
    statusFree: '無料版',
    statusSupporter: 'サポーター',
    bookmarkSave: 'ブックマーク保存',
    bookmarkList: 'ブックマーク一覧',
    bookmarkModalTitle: 'ブックマーク一覧',
    bookmarkSaved: 'ブックマークを保存しました。',
    bookmarkDeleted: 'ブックマークを削除しました。',
    bookmarkPremiumOnly: 'ブックマークはサポーター専用の機能です。',
    bookmarkSavedAt: '保存日時：',
    bookmarkSaveFirst: '比較結果を表示してから保存してください。',
    bookmarkLimitReached: 'ブックマークは最大100件までです。不要なものを削除してください。',
    bookmarkSaveFailed: 'ブックマーク保存に失敗しました。',
    bookmarkLoading: '読み込み中...',
    bookmarkEmpty: '保存済みブックマークはありません。',
    bookmarkOpen: '開く',
    bookmarkDelete: '削除',
    bookmarkDeleting: '削除中...',
    bookmarkDeleteFailed: '削除に失敗しました。',
    bookmarkListFailed: 'ブックマーク一覧の取得に失敗しました。',
    usageLimitReached: '1日30回の上限に達しました。サポーターなら無制限です。',
    usageCheckFailed: '利用回数の確認に失敗しました。時間をおいて再度お試しください。',
  },
};



function t(key) { return I18N[state.lang]?.[key] ?? I18N.en[key] ?? key; }

const state = {
  iconMap: [],
  lang: 'ja',
  urlA: null,
  urlB: null,
  reportA: null,
  reportB: null,
  selectedFightA: null,
  selectedFightB: null,
  playersA: [],
  playersB: [],
  selectedA: null,
  selectedB: null,
  isPremium: false,
  currentTab: 'all',
  timelineA: [],
  timelineB: [],
  timelineCountA: 0,
  timelineCountB: 0,
  compareError: null,
  actionById: new Map(),
  abilityById: new Map(),
  zoom: 2.5,
  damageA: [],
  damageB: [],
  healingA: [],
  healingB: [],
  partyBuffsA: [],
  partyBuffsB: [],
  rollingDpsA: [],
  rollingDpsB: [],
  phasesA: [],
  phasesB: [],
  phases: [],
  currentPhase: null,
  dpsDataA: null,
  dpsDataB: null,
  fightA: null,
  fightB: null,
  tutorial: {
    active: false,
    stepIndex: 0,
    highlightKey: '',
  },
};
const el = {
  tutorialBtn: document.getElementById('tutorialBtn'),
  contactBtn: document.getElementById('contactBtn'),
  privacyLink: document.getElementById('privacyLink'),
  publicOnlyNote: document.getElementById('publicOnlyNote'),
  urlA: document.getElementById('urlA'),
  urlB: document.getElementById('urlB'),
  loadBtn: document.getElementById('loadBtn'),
  loadPlayersBtn: document.getElementById('loadPlayersBtn'),
  compareBtn: document.getElementById('compareBtn'),
  step2: document.getElementById('step2'),
  step3: document.getElementById('step3'),
  step4: document.getElementById('step4'),
  msg: document.getElementById('step1Message'),
  step2Message: document.getElementById('step2Message'),
  step4Message: document.getElementById('step4Message'),
  fightA: document.getElementById('fightA'),
  fightB: document.getElementById('fightB'),
  playerA: document.getElementById('playerA'),
  playerB: document.getElementById('playerB'),
  tabs: [...document.querySelectorAll('.tab')],
  timelineWrap: document.getElementById('timelineWrap'),
  zoomInBtn: document.getElementById('zoomInBtn'),
  zoomOutBtn: document.getElementById('zoomOutBtn'),
  zoomLabel: document.getElementById('zoomLabel'),
  phaseContainer: document.getElementById('phaseContainer'),
  bookmarkControls: document.getElementById('bookmarkControls'),
  saveBookmarkBtn: document.getElementById('saveBookmarkBtn'),
  showBookmarksBtn: document.getElementById('showBookmarksBtn'),
  bookmarkModal: document.getElementById('bookmarkModal'),
  bookmarkModalBackdrop: document.getElementById('bookmarkModalBackdrop'),
  bookmarkModalCloseBtn: document.getElementById('bookmarkModalCloseBtn'),
  bookmarkList: document.getElementById('bookmarkList'),
  bookmarkMessage: document.getElementById('bookmarkMessage'),
  bookmarkModalTitle: document.getElementById('bookmarkModalTitle'),
  uiToast: document.getElementById('uiToast'),
  debugLog: document.getElementById('debugLog'),
  errorLog: document.getElementById('errorLog'),
  tutorialOverlay: document.getElementById('tutorialOverlay'),
  tutorialBackdrop: document.getElementById('tutorialBackdrop'),
  tutorialCard: document.getElementById('tutorialCard'),
  tutorialStepMeta: document.getElementById('tutorialStepMeta'),
  tutorialTitle: document.getElementById('tutorialTitle'),
  tutorialBody: document.getElementById('tutorialBody'),
  tutorialStatus: document.getElementById('tutorialStatus'),
  tutorialPrevBtn: document.getElementById('tutorialPrevBtn'),
  tutorialNextBtn: document.getElementById('tutorialNextBtn'),
  tutorialCloseBtn: document.getElementById('tutorialCloseBtn'),
  langToggle: document.getElementById('langToggle'),
  siteTitle: document.getElementById('siteTitle'),
  siteDesc: document.getElementById('siteDesc'),
  step1Title: document.getElementById('step1Title'),
  step2Title: document.getElementById('step2Title'),
  step3Title: document.getElementById('step3Title'),
  step4Title: document.getElementById('step4Title'),
  debugNormalTitle: document.getElementById('debugNormalTitle'),
  debugErrorTitle: document.getElementById('debugErrorTitle'),
  logUrlALabel: document.getElementById('logUrlALabel'),
  logUrlBLabel: document.getElementById('logUrlBLabel'),
  logAFightLabel: document.getElementById('logAFightLabel'),
  logBFightLabel: document.getElementById('logBFightLabel'),
  logAPlayerLabel: document.getElementById('logAPlayerLabel'),
  logBPlayerLabel: document.getElementById('logBPlayerLabel'),
};
function bindClick(node, name, handler) {
  if (!node) {
    return;
  }
  node.addEventListener('click', handler);
}
function logDebug(message, payload = null) {
  const t = new Date().toLocaleTimeString();
  const line = payload ? `[${t}] ${message} ${JSON.stringify(payload).slice(0, 500)}` : `[${t}] ${message}`;
  el.debugLog.textContent += line + "\n";
  el.debugLog.scrollTop = el.debugLog.scrollHeight;
}
function logError(message, payload = null) {
  const time = new Date().toLocaleTimeString();
  const line = payload
    ? `[${time}] ${message} ${JSON.stringify(payload).slice(0, 500)}`
    : `[${time}] ${message}`;
  el.errorLog.textContent += line + "\n";
  el.errorLog.scrollTop = el.errorLog.scrollHeight;
}

// Expose module-scoped declarations to globalThis for consuming modules.
// Required during the side-effect module stage of the ESM migration;
// removed once each consumer switches to explicit imports.
Object.assign(globalThis, {
  TUTORIAL_STATE_KEY,
  JOB_CODE_MAP,
  BURST_BUFFS,
  SELF_BUFFS,
  JOB_NAME_JA,
  JOB_ROLE,
  JOB_SHORT_JA,
  ROLE_ORDER,
  I18N,
  t,
  state,
  el,
  bindClick,
  logDebug,
  logError,
});
