// Core constants, state, DOM bindings, and debug helpers

const TUTORIAL_STATE_KEY = 'ffxiv_rotation_diff_tutorial';

const JOB_CODE_MAP = {
  PALADIN: 'PLD', WARRIOR: 'WAR', DARKKNIGHT: 'DRK', GUNBREAKER: 'GNB',
  WHITEMAGE: 'WHM', SCHOLAR: 'SCH', ASTROLOGIAN: 'AST', SAGE: 'SGE',
  MONK: 'MNK', DRAGOON: 'DRG', NINJA: 'NIN', SAMURAI: 'SAM', REAPER: 'RPR', VIPER: 'VPR',
  BARD: 'BRD', MACHINIST: 'MCH', DANCER: 'DNC',
  BLACKMAGE: 'BLM', SUMMONER: 'SMN', REDMAGE: 'RDM', PICTOMANCER: 'PCT',
  // already-abbreviated pass-through
  PLD: 'PLD', WAR: 'WAR', DRK: 'DRK', GNB: 'GNB',
  WHM: 'WHM', SCH: 'SCH', AST: 'AST', SGE: 'SGE',
  MNK: 'MNK', DRG: 'DRG', NIN: 'NIN', SAM: 'SAM', RPR: 'RPR', VPR: 'VPR',
  BRD: 'BRD', MCH: 'MCH', DNC: 'DNC',
  BLM: 'BLM', SMN: 'SMN', RDM: 'RDM', PCT: 'PCT',
};

const BURST_BUFFS = [
  { ids: [7398],  nameEn: 'Battle Litany',    nameJa: 'バトルリタニー',      duration: 20, color: '#60a5fa' },
  { ids: [7396],  nameEn: 'Brotherhood',       nameJa: '桃園結義',           duration: 20, color: '#f472b6' },
  { ids: [16552], nameEn: 'Divination',        nameJa: 'ディヴィネーション',   duration: 20, color: '#fbbf24' },
  { ids: [7436],  nameEn: 'Chain Stratagem',   nameJa: '連環計',             duration: 20, color: '#a78bfa' },
  { ids: [7520],  nameEn: 'Embolden',          nameJa: 'エンボルデン',        duration: 20, color: '#f87171' },
  { ids: [24405], nameEn: 'Arcane Circle',     nameJa: 'アルカナサークル',     duration: 20, color: '#c084fc' },
  { ids: [15998], nameEn: 'Technical Finish',  nameJa: 'テクニカルフィニッシュ', duration: 20, color: '#34d399' },
  { ids: [25801], nameEn: 'Searing Light',     nameJa: 'シアリングライト',     duration: 20, color: '#fcd34d' },
  { ids: [25785], nameEn: 'Radiant Finale',    nameJa: 'ラジアントフィナーレ',  duration: 20, color: '#fb923c' },
  { ids: [34681], nameEn: 'Starry Muse',       nameJa: 'スターリーミューズ',    duration: 20, color: '#38bdf8' },
  { ids: [36871], nameEn: 'Dokumori',          nameJa: '毒盛り',             duration: 20, color: '#86efac' },
];

const SELF_BUFFS = [
  { nameEn: 'Fight or Flight',  nameJa: 'ファイト・オア・フライト', duration: 20, color: '#fbbf24' },
  { nameEn: 'Inner Release',    nameJa: '原初の解放',             duration: 15, color: '#ef4444' },
  { nameEn: 'Blood Weapon',     nameJa: 'ブラッドウェポン',       duration: 15, color: '#dc2626' },
  { nameEn: 'Delirium',         nameJa: 'ブラッドデリリアム',      duration: 15, color: '#b91c1c' },
  { nameEn: 'No Mercy',         nameJa: 'ノー・マーシー',         duration: 20, color: '#f59e0b' },
  { nameEn: 'Riddle of Fire',   nameJa: '紅蓮の極意',            duration: 20, color: '#ea580c' },
  { nameEn: 'Lance Charge',     nameJa: 'ランスチャージ',         duration: 20, color: '#3b82f6' },
  { nameEn: 'Raging Strikes',   nameJa: '猛者の撃',             duration: 20, color: '#f97316' },
  { nameEn: 'Wildfire',         nameJa: 'ワイルドファイア',       duration: 10, color: '#ef4444' },
  { nameEn: 'Devilment',        nameJa: '攻めのタンゴ',          duration: 20, color: '#ec4899' },
  { nameEn: 'Ley Lines',        nameJa: '黒魔紋',               duration: 30, color: '#8b5cf6' },
  { nameEn: 'Manafication',     nameJa: 'マナフィケーション',     duration: 15, color: '#6366f1' },
  { nameEn: 'Meikyo Shisui',    nameJa: '明鏡止水',             duration: 15, color: '#06b6d4' },
];

const JOB_NAME_JA = {
  PLD:'ナイト', WAR:'戦士', DRK:'暗黒騎士', GNB:'ガンブレイカー',
  WHM:'白魔道士', SCH:'学者', AST:'占星術師', SGE:'賢者',
  MNK:'モンク', DRG:'竜騎士', NIN:'忍者', SAM:'侍', RPR:'リーパー', VPR:'ヴァイパー',
  BRD:'吟遊詩人', MCH:'機工士', DNC:'踊り子',
  BLM:'黒魔道士', SMN:'召喚士', RDM:'赤魔道士', PCT:'ピクトマンサー',
};

const JOB_ROLE = {
  PLD:'T', WAR:'T', DRK:'T', GNB:'T',
  WHM:'H', SCH:'H', AST:'H', SGE:'H',
  MNK:'D', DRG:'D', NIN:'D', SAM:'D', RPR:'D', VPR:'D',
  BRD:'D', MCH:'D', DNC:'D',
  BLM:'D', SMN:'D', RDM:'D', PCT:'D',
};

const JOB_SHORT_JA = {
  PLD:'ナ', WAR:'戦', DRK:'暗', GNB:'ガ',
  WHM:'白', SCH:'学', AST:'占', SGE:'賢',
  MNK:'モ', DRG:'竜', NIN:'忍', SAM:'侍', RPR:'リ', VPR:'ヴ',
  BRD:'詩', MCH:'機', DNC:'踊',
  BLM:'黒', SMN:'召', RDM:'赤', PCT:'ピ',
};

const ROLE_ORDER = ['T','H','D'];

const DEBUFF_IDS = {
  damageDown: { nameEn: 'Damage Down', nameJa: '与ダメージ低下', color: '#ef4444' },
  weakness:   { nameEn: 'Weakness',    nameJa: '衰弱',         color: '#f59e0b' },
  brink:      { nameEn: 'Brink of Death', nameJa: '衰弱[強]',  color: '#dc2626' },
};

const I18N = {
  en: {
    siteTitle: 'FFXIV Skill Rotation Diff',
    siteDesc: 'Compare skill rotations from 2 public FFLogs URLs',
    step1Title: '1. Load Public FFLogs Logs',
    publicOnlyNote: 'Public FFLogs logs only. No FFLogs sign-in is required.',
    logUrlA: 'Log URL A',
    logUrlB: 'Log URL B',
    loadBtn: 'Load Reports',
    step2Title: '2. Select Fight Data (Kill only)',
    logAFight: 'Log A Fight',
    logBFight: 'Log B Fight',
    loadPlayersBtn: 'Get Players for This Fight',
    step3Title: '3. Select Players to Compare',
    logAPlayer: 'Log A Player',
    logBPlayer: 'Log B Player',
    compareBtn: 'Start Comparison',
    step4Title: '4. Comparison Results',
    tabAll: 'Full TL',
    tabOdd: 'Odd Min TL',
    tabEven: 'Even Min TL',
    laneAbility: 'Ability',
    laneGcd: 'WS / Spell',
    laneDebuff: 'Debuff',
    laneBoss: 'Boss Cast',
    debugNormalTitle: 'Log',
    debugErrorTitle: 'Error Log',
    tutorialBtn: 'First time here?',
    tutorialPrev: 'Back',
    tutorialNext: 'Next',
    tutorialFinish: 'Done',
    tutorialClose: 'Close',
    tutorialWaiting: 'Waiting for this step to be completed.',
    tutorialReady: 'Completed. Move to the next step.',
    tutorialIntroTitle: 'Quick Start Guide',
    tutorialIntroBody: 'This guide walks you through the minimum steps needed to load two public logs and reach the comparison timeline.',
    tutorialLoadReportsTitle: '1. Enter two public log URLs',
    tutorialLoadReportsBody: 'Paste one FFLogs report URL into A and one into B, then load the reports. When the fight selectors appear, this step is complete.',
    tutorialLoadPlayersTitle: '2. Choose fights and load players',
    tutorialLoadPlayersBody: 'Pick the fight you want to compare from each log, then load the player list for both sides.',
    tutorialCompareTitle: '3. Choose players and start comparison',
    tutorialCompareBody: 'Select one player from each log and run the comparison. When the timeline panel opens, the main setup is complete.',
    tutorialDoneTitle: 'Guide Complete',
    tutorialDoneBody: 'The comparison view is now ready. You can switch tabs, change phase filters, zoom, and inspect the timeline freely.',
    tutorialStep: (current, total) => `Step ${current} / ${total}`,
    footerNote: 'Note: Public FFLogs logs only. Paste two report URLs, then select a fight and players.',
    badUrl: 'Please check FFLogs URL format.',
    loading: 'Loading reports...',
    killFightsLoaded: (a,b) => `Kill fights loaded: A=${a} / B=${b}`,
    playersLoaded: (a,b) => `Players loaded: A=${a} / B=${b}`,
    tlLoading: 'Loading player timeline...',
    tlLoaded: (a,b) => `TL loaded: A=${a} / B=${b}`,
    kill: 'Kill',
    wipe: 'Wipe',
    encounterMismatch: 'Cannot compare different bosses. Please select the same encounter.',
    phaseAll: 'All Phases',
  },
  ja: {
    siteTitle: 'FFXIV スキル回し比較',
    siteDesc: 'FFLogs の公開ログ URL 2 件からスキル回しを比較します',
    step1Title: '1. 公開 FFLogs ログを読み込む',
    logUrlA: 'ログURL A',
    logUrlB: 'ログURL B',
    loadBtn: '読み込み開始',
    step2Title: '2. 戦闘データ選択（Kill のみ）',
    logAFight: 'ログA 戦闘',
    logBFight: 'ログB 戦闘',
    loadPlayersBtn: 'この戦闘でプレイヤー一覧を取得',
    step3Title: '3. 比較するプレイヤー選択',
    logAPlayer: 'ログAプレイヤー',
    logBPlayer: 'ログBプレイヤー',
    compareBtn: '比較を開始',
    step4Title: '4. 比較結果',
    tabAll: '全体TL',
    tabOdd: '奇数分TL',
    tabEven: '偶数分TL',
    laneAbility: 'アビリティ',
    laneGcd: 'WS・魔法',
    laneDebuff: 'デバフ',
    laneBoss: 'ボス詠唱',
    debugNormalTitle: 'ログ',
    debugErrorTitle: 'エラーログ',
    publicOnlyNote: '公開ログのみ対応です。FFLogs の連携は不要です。',
    footerNote: '注: 公開 FFLogs ログのみ対応しています。2つのレポート URL を入力し、戦闘とプレイヤーを選択してください。',
    badUrl: 'FFLogs URL形式を確認してください。',
    loading: 'レポートを読み込み中...',
    killFightsLoaded: (a,b) => `Kill戦闘一覧取得成功: A=${a}件 / B=${b}件`,
    playersLoaded: (a,b) => `プレイヤー取得成功: A=${a}人 / B=${b}人`,
    tlLoading: '選択プレイヤーのTLを取得中...',
    tlLoaded: (a,b) => `TL取得成功: A=${a}件 / B=${b}件`,
    kill: 'Kill',
    wipe: 'Wipe',
    encounterMismatch: '異なるボスの戦闘は比較できません。同じ敵を選択してください。',
    phaseAll: '全フェーズ',
  },
};

Object.assign(I18N.en, {
  siteDesc: 'Compare skill rotations from 2 public FFLogs URLs',
  step1Title: '1. Load Public FFLogs Logs',
  publicOnlyNote: 'Public FFLogs logs only. No FFLogs sign-in is required.',
  tutorialIntroBody: 'This guide walks you through the minimum steps needed to load two public logs and reach the comparison timeline.',
  tutorialLoadReportsTitle: '1. Enter two public log URLs',
  tutorialLoadPlayersTitle: '2. Choose fights and load players',
  tutorialCompareTitle: '3. Choose players and start comparison',
  footerNote: 'Note: Public FFLogs logs only. Paste two report URLs, then select a fight and players.',
  loading: 'Loading reports...',
});

Object.assign(I18N.ja, {
  siteTitle: 'FFXIV スキル回し比較',
  siteDesc: 'FFLogs の公開ログ URL 2 件からスキル回しを比較します',
  step1Title: '1. 公開 FFLogs ログを読み込む',
  publicOnlyNote: '公開ログのみ対応です。FFLogs の連携は不要です。',
  loadBtn: '読み込み開始',
  step2Title: '2. 戦闘データ選択（Kill のみ）',
  logAFight: 'ログA 戦闘',
  logBFight: 'ログB 戦闘',
  loadPlayersBtn: 'この戦闘でプレイヤー一覧を取得',
  step3Title: '3. 比較するプレイヤー選択',
  compareBtn: '比較を開始',
  step4Title: '4. 比較結果',
  tabAll: '全体TL',
  tabOdd: '奇数分TL',
  tabEven: '偶数分TL',
  laneAbility: 'アビリティ',
  laneGcd: 'WS / 魔法',
  laneDebuff: 'デバフ',
  laneBoss: 'ボス詠唱',
  debugNormalTitle: 'ログ',
  debugErrorTitle: 'エラーログ',
  tutorialIntroTitle: 'クイックスタートガイド',
  tutorialIntroBody: 'このガイドでは、2つの公開ログを読み込んで比較タイムラインを表示するまでの最小手順を案内します。',
  tutorialLoadReportsTitle: '1. 公開ログ URL を 2 つ入力する',
  tutorialLoadReportsBody: 'A と B に FFLogs のレポート URL を 1 つずつ貼り付けて読み込みます。戦闘セレクトが表示されたら完了です。',
  tutorialLoadPlayersTitle: '2. 戦闘を選んでプレイヤーを取得する',
  tutorialLoadPlayersBody: 'A / B それぞれで比較したい戦闘を選び、プレイヤー一覧を取得してください。',
  tutorialCompareTitle: '3. プレイヤーを選んで比較する',
  tutorialCompareBody: '両方のログから 1 人ずつ選び、比較を開始します。タイムラインが表示されたら準備完了です。',
  tutorialDoneTitle: 'ガイド完了',
  tutorialDoneBody: '比較表示まで完了しました。ここからはタブ切替、フェーズ選択、ズーム、ログ確認を自由に使えます。',
  footerNote: '注: 公開 FFLogs ログのみ対応しています。2つのレポート URL を入力し、戦闘とプレイヤーを選択してください。',
  badUrl: 'FFLogs URL形式を確認してください。',
  loading: 'レポートを読み込み中...',
  killFightsLoaded: (a,b) => `Kill戦闘一覧取得成功: A=${a}件 / B=${b}件`,
  playersLoaded: (a,b) => `プレイヤー一覧取得成功: A=${a}人 / B=${b}人`,
  tlLoading: '選択プレイヤーのTLを取得中...',
  tlLoaded: (a,b) => `TL取得成功: A=${a}件 / B=${b}件`,
  encounterMismatch: '異なるボス同士の比較はできません。同じ encounter を選択してください。',
  phaseAll: '全フェーズ',
});

function t(key) { return I18N[state.lang]?.[key] ?? I18N.en[key] ?? key; }

const state = {
  iconMap: [],
  lang: 'ja',
  urlA: null,
  urlB: null,
  reportA: null,
  reportB: null,
  selectedFightA: null,
  selectedFightB: null,
  playersA: [],
  playersB: [],
  selectedA: null,
  selectedB: null,
  currentTab: 'all',
  timelineA: [],
  timelineB: [],
  timelineCountA: 0,
  timelineCountB: 0,
  actionById: new Map(),
  abilityById: new Map(),
  zoom: 2,
  damageA: [],
  damageB: [],
  bossCastsA: [],
  bossCastsB: [],
  debuffsA: [],
  debuffsB: [],
  partyBuffsA: [],
  partyBuffsB: [],
  rollingDpsA: [],
  rollingDpsB: [],
  phasesA: [],
  phasesB: [],
  phases: [],
  currentPhase: null,
  dpsDataA: null,
  dpsDataB: null,
  fightA: null,
  fightB: null,
  tutorial: {
    active: false,
    stepIndex: 0,
    highlightKey: '',
  },
};
const el = {
  tutorialBtn: document.getElementById('tutorialBtn'),
  publicOnlyNote: document.getElementById('publicOnlyNote'),
  urlA: document.getElementById('urlA'),
  urlB: document.getElementById('urlB'),
  loadBtn: document.getElementById('loadBtn'),
  loadPlayersBtn: document.getElementById('loadPlayersBtn'),
  compareBtn: document.getElementById('compareBtn'),
  step2: document.getElementById('step2'),
  step3: document.getElementById('step3'),
  step4: document.getElementById('step4'),
  msg: document.getElementById('step1Message'),
  step2Message: document.getElementById('step2Message'),
  fightA: document.getElementById('fightA'),
  fightB: document.getElementById('fightB'),
  playerA: document.getElementById('playerA'),
  playerB: document.getElementById('playerB'),
  tabs: [...document.querySelectorAll('.tab')],
  timelineWrap: document.getElementById('timelineWrap'),
  zoomInBtn: document.getElementById('zoomInBtn'),
  zoomOutBtn: document.getElementById('zoomOutBtn'),
  zoomLabel: document.getElementById('zoomLabel'),
  phaseContainer: document.getElementById('phaseContainer'),
  debugLog: document.getElementById('debugLog'),
  errorLog: document.getElementById('errorLog'),
  tutorialOverlay: document.getElementById('tutorialOverlay'),
  tutorialBackdrop: document.getElementById('tutorialBackdrop'),
  tutorialCard: document.getElementById('tutorialCard'),
  tutorialStepMeta: document.getElementById('tutorialStepMeta'),
  tutorialTitle: document.getElementById('tutorialTitle'),
  tutorialBody: document.getElementById('tutorialBody'),
  tutorialStatus: document.getElementById('tutorialStatus'),
  tutorialPrevBtn: document.getElementById('tutorialPrevBtn'),
  tutorialNextBtn: document.getElementById('tutorialNextBtn'),
  tutorialCloseBtn: document.getElementById('tutorialCloseBtn'),
  langToggle: document.getElementById('langToggle'),
  siteTitle: document.getElementById('siteTitle'),
  siteDesc: document.getElementById('siteDesc'),
  step1Title: document.getElementById('step1Title'),
  step2Title: document.getElementById('step2Title'),
  step3Title: document.getElementById('step3Title'),
  step4Title: document.getElementById('step4Title'),
  debugNormalTitle: document.getElementById('debugNormalTitle'),
  debugErrorTitle: document.getElementById('debugErrorTitle'),
  footerNote: document.getElementById('footerNote'),
  logUrlALabel: document.getElementById('logUrlALabel'),
  logUrlBLabel: document.getElementById('logUrlBLabel'),
  logAFightLabel: document.getElementById('logAFightLabel'),
  logBFightLabel: document.getElementById('logBFightLabel'),
  logAPlayerLabel: document.getElementById('logAPlayerLabel'),
  logBPlayerLabel: document.getElementById('logBPlayerLabel'),
};
function bindClick(node, name, handler) {
  if (!node) {
    return;
  }
  node.addEventListener('click', handler);
}
function logDebug(message, payload = null) {
  const t = new Date().toLocaleTimeString();
  const line = payload ? `[${t}] ${message} ${JSON.stringify(payload).slice(0, 500)}` : `[${t}] ${message}`;
  el.debugLog.textContent += line + "\n";
  el.debugLog.scrollTop = el.debugLog.scrollHeight;
}
function logError(message, payload = null) {
  const time = new Date().toLocaleTimeString();
  const line = payload
    ? `[${time}] ${message} ${JSON.stringify(payload).slice(0, 500)}`
    : `[${time}] ${message}`;
  el.errorLog.textContent += line + "\n";
  el.errorLog.scrollTop = el.errorLog.scrollHeight;
}
