create table if not exists public.analysis_reports (
  id bigint generated by default as identity primary key,
  period_start timestamptz not null,
  period_end timestamptz not null,
  report_md text not null,
  analytics_snapshot jsonb not null default '{}'::jsonb,
  feedback_snapshot jsonb not null default '{}'::jsonb,
  model text not null default '',
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists analysis_reports_created_at_idx
  on public.analysis_reports (created_at desc);
