create table if not exists public.billing_customers (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stripe_customer_id text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.billing_subscriptions (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  stripe_customer_id text not null,
  status text not null,
  current_period_end timestamptz not null,
  cancel_at_period_end boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists billing_subscriptions_user_id_idx on public.billing_subscriptions(user_id);

create table if not exists public.comparison_daily_usage (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade,
  anon_key text,
  usage_date date not null,
  count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint chk_usage_owner check (user_id is not null or anon_key is not null)
);
create unique index if not exists usage_user_date_idx on public.comparison_daily_usage(user_id, usage_date) where user_id is not null;
create unique index if not exists usage_anon_date_idx on public.comparison_daily_usage(anon_key, usage_date) where anon_key is not null;

create table if not exists public.comparison_bookmarks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default '',
  data jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists comparison_bookmarks_user_id_idx on public.comparison_bookmarks(user_id);

create table if not exists public.stripe_webhook_events (
  id bigint generated by default as identity primary key,
  stripe_event_id text not null unique,
  type text not null,
  payload jsonb not null,
  processed_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.billing_customers enable row level security;
create policy "users can read own billing customer" on public.billing_customers
  for select using (auth.uid() = user_id);

alter table public.billing_subscriptions enable row level security;
create policy "users can read own subscriptions" on public.billing_subscriptions
  for select using (auth.uid() = user_id);

alter table public.comparison_daily_usage enable row level security;
create policy "users can read own usage" on public.comparison_daily_usage
  for select using (auth.uid() = user_id);

alter table public.comparison_bookmarks enable row level security;
create policy "users can manage own bookmarks" on public.comparison_bookmarks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

alter table public.stripe_webhook_events enable row level security;
-- ポリシーを一切作成しない（RLS有効化のみでユーザーは全アクセス不可）
