create table if not exists public.app_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  pathname text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc'::text, now())
);

create index if not exists app_events_created_at_idx
  on public.app_events (created_at desc);

create index if not exists app_events_event_type_idx
  on public.app_events (event_type);

alter table public.app_events enable row level security;
alter table public.feedback_entries enable row level security;
alter table public.feedback_rate_limits enable row level security;
alter table public.analysis_reports enable row level security;

create or replace function public.check_and_increment_comparison_usage(
  p_user_id uuid,
  p_anon_key text,
  p_usage_date date,
  p_daily_limit integer
)
returns table(allowed boolean, count integer, remaining integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id bigint;
  v_count integer;
  v_owner_key text;
begin
  if p_user_id is null and coalesce(p_anon_key, '') = '' then
    raise exception 'user_id or anon_key is required';
  end if;

  v_owner_key := coalesce(p_user_id::text, p_anon_key);
  perform pg_advisory_xact_lock(hashtextextended(v_owner_key || ':' || p_usage_date::text, 0));

  if p_user_id is not null then
    select usage.id, usage.count into v_id, v_count
    from public.comparison_daily_usage as usage
    where usage.user_id = p_user_id and usage.usage_date = p_usage_date
    limit 1;
  else
    select usage.id, usage.count into v_id, v_count
    from public.comparison_daily_usage as usage
    where usage.anon_key = p_anon_key and usage.usage_date = p_usage_date
    limit 1;
  end if;

  v_count := coalesce(v_count, 0);

  if v_count >= p_daily_limit then
    allowed := false;
    count := v_count;
    remaining := 0;
    return next;
    return;
  end if;

  v_count := v_count + 1;

  if v_id is null then
    insert into public.comparison_daily_usage(user_id, anon_key, usage_date, count)
    values (p_user_id, case when p_user_id is null then p_anon_key else null end, p_usage_date, v_count);
  else
    update public.comparison_daily_usage
    set count = v_count,
        updated_at = now()
    where id = v_id;
  end if;

  allowed := true;
  count := v_count;
  remaining := greatest(0, p_daily_limit - v_count);
  return next;
end;
$$;

create or replace function public.check_and_increment_feedback_rate_limit(
  p_ip_hash text,
  p_window_started_at timestamptz,
  p_now timestamptz,
  p_limit integer default 5
)
returns table(allowed boolean, request_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_count integer;
begin
  if coalesce(p_ip_hash, '') = '' then
    raise exception 'ip_hash is required';
  end if;

  delete from public.feedback_rate_limits
  where window_started_at < p_now - interval '10 minutes';

  perform pg_advisory_xact_lock(hashtextextended(p_ip_hash || ':' || p_window_started_at::text, 0));

  select feedback_rate_limits.request_count into v_count
  from public.feedback_rate_limits
  where ip_hash = p_ip_hash and window_started_at = p_window_started_at
  limit 1;

  v_count := coalesce(v_count, 0);

  if v_count >= p_limit then
    allowed := false;
    request_count := v_count;
    return next;
    return;
  end if;

  v_count := v_count + 1;

  insert into public.feedback_rate_limits(ip_hash, window_started_at, request_count, updated_at)
  values (p_ip_hash, p_window_started_at, v_count, p_now)
  on conflict (ip_hash, window_started_at)
  do update set request_count = v_count, updated_at = p_now;

  allowed := true;
  request_count := v_count;
  return next;
end;
$$;

revoke all on function public.check_and_increment_comparison_usage(uuid, text, date, integer) from public;
revoke all on function public.check_and_increment_feedback_rate_limit(text, timestamptz, timestamptz, integer) from public;
grant execute on function public.check_and_increment_comparison_usage(uuid, text, date, integer) to service_role;
grant execute on function public.check_and_increment_feedback_rate_limit(text, timestamptz, timestamptz, integer) to service_role;
