create table if not exists public.feedback_entries (
  id bigint generated by default as identity primary key,
  category text not null,
  subject text not null,
  body text not null,
  bucket text not null default 'general',
  ai_reason text not null default '',
  admin_note text not null default '',
  is_read boolean not null default false,
  read_at timestamptz,
  delete_after_at timestamptz,
  ip_hash text,
  moderation_provider text not null default '',
  moderation_model text not null default '',
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.feedback_rate_limits (
  ip_hash text not null,
  window_started_at timestamptz not null,
  request_count integer not null default 0,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  primary key (ip_hash, window_started_at)
);
